package com.example.campus.mapper;

import com.example.campus.entity.Comment;
import com.example.campus.entity.Message;

import java.sql.Timestamp;
import java.util.List;


public interface MessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated Tue Jun 09 02:45:56 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated Tue Jun 09 02:45:56 CST 2020
     */
    int insert(Message record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated Tue Jun 09 02:45:56 CST 2020
     */
    int insertSelective(Message record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated Tue Jun 09 02:45:56 CST 2020
     */
    Message selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated Tue Jun 09 02:45:56 CST 2020
     */
    int updateByPrimaryKeySelective(Message record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated Tue Jun 09 02:45:56 CST 2020
     */
    int updateByPrimaryKey(Message record);

    int creatMsg(String content, Timestamp PublishTime, String AcceptClass);
    List<List<Message>> getAllMsg(String searchInfo, int start, int end);
}