package com.example.campus.mapper;

import com.example.campus.entity.User;

import java.util.List;
import java.util.Map;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Tue Jun 02 17:06:36 CST 2020
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Tue Jun 02 17:06:36 CST 2020
     */
    int insUser(User record);

    User selectByPrimaryKey(String userno);
    User selectUserByUserNo(Map<String,String> map);
    List<User> getAllUsers();
    List<String> getAllClass();

    String selColletionByUserId(String userId);

    int updColletion(String userId,String collection);
}