package com.example.campus.entity;

public class Comment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.CommentId
     *
     * @mbg.generated Tue Jun 02 17:06:36 CST 2020
     */
    private Integer commentid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.CommentDetail
     *
     * @mbg.generated Tue Jun 02 17:06:36 CST 2020
     */
    private String commentdetail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.UserId
     *
     * @mbg.generated Tue Jun 02 17:06:36 CST 2020
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.PostId
     *
     * @mbg.generated Tue Jun 02 17:06:36 CST 2020
     */
    private Integer postid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.IsResonse
     *
     * @mbg.generated Tue Jun 02 17:06:36 CST 2020
     */
    private Integer isresonse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.ResonseId
     *
     * @mbg.generated Tue Jun 02 17:06:36 CST 2020
     */
    private Integer resonseid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.Goods
     *
     * @mbg.generated Tue Jun 02 17:06:36 CST 2020
     */
    private Integer goods;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.Bads
     *
     * @mbg.generated Tue Jun 02 17:06:36 CST 2020
     */
    private Integer bads;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.CommentId
     *
     * @return the value of comment.CommentId
     *
     * @mbg.generated Tue Jun 02 17:06:36 CST 2020
     */
    public Integer getCommentid() {
        return commentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.CommentId
     *
     * @param commentid the value for comment.CommentId
     *
     * @mbg.generated Tue Jun 02 17:06:36 CST 2020
     */
    public void setCommentid(Integer commentid) {
        this.commentid = commentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.CommentDetail
     *
     * @return the value of comment.CommentDetail
     *
     * @mbg.generated Tue Jun 02 17:06:36 CST 2020
     */
    public String getCommentdetail() {
        return commentdetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.CommentDetail
     *
     * @param commentdetail the value for comment.CommentDetail
     *
     * @mbg.generated Tue Jun 02 17:06:36 CST 2020
     */
    public void setCommentdetail(String commentdetail) {
        this.commentdetail = commentdetail == null ? null : commentdetail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.UserId
     *
     * @return the value of comment.UserId
     *
     * @mbg.generated Tue Jun 02 17:06:36 CST 2020
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.UserId
     *
     * @param userid the value for comment.UserId
     *
     * @mbg.generated Tue Jun 02 17:06:36 CST 2020
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.PostId
     *
     * @return the value of comment.PostId
     *
     * @mbg.generated Tue Jun 02 17:06:36 CST 2020
     */
    public Integer getPostid() {
        return postid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.PostId
     *
     * @param postid the value for comment.PostId
     *
     * @mbg.generated Tue Jun 02 17:06:36 CST 2020
     */
    public void setPostid(Integer postid) {
        this.postid = postid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.IsResonse
     *
     * @return the value of comment.IsResonse
     *
     * @mbg.generated Tue Jun 02 17:06:36 CST 2020
     */
    public Integer getIsresonse() {
        return isresonse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.IsResonse
     *
     * @param isresonse the value for comment.IsResonse
     *
     * @mbg.generated Tue Jun 02 17:06:36 CST 2020
     */
    public void setIsresonse(Integer isresonse) {
        this.isresonse = isresonse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.ResonseId
     *
     * @return the value of comment.ResonseId
     *
     * @mbg.generated Tue Jun 02 17:06:36 CST 2020
     */
    public Integer getResonseid() {
        return resonseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.ResonseId
     *
     * @param resonseid the value for comment.ResonseId
     *
     * @mbg.generated Tue Jun 02 17:06:36 CST 2020
     */
    public void setResonseid(Integer resonseid) {
        this.resonseid = resonseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.Goods
     *
     * @return the value of comment.Goods
     *
     * @mbg.generated Tue Jun 02 17:06:36 CST 2020
     */
    public Integer getGoods() {
        return goods;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.Goods
     *
     * @param goods the value for comment.Goods
     *
     * @mbg.generated Tue Jun 02 17:06:36 CST 2020
     */
    public void setGoods(Integer goods) {
        this.goods = goods;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.Bads
     *
     * @return the value of comment.Bads
     *
     * @mbg.generated Tue Jun 02 17:06:36 CST 2020
     */
    public Integer getBads() {
        return bads;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.Bads
     *
     * @param bads the value for comment.Bads
     *
     * @mbg.generated Tue Jun 02 17:06:36 CST 2020
     */
    public void setBads(Integer bads) {
        this.bads = bads;
    }
}