package com.example.campus.entity;

import lombok.Builder;

import java.util.Date;

@Builder
public class Post {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.PostId
     *
     * @mbg.generated Wed Jun 10 22:24:16 CST 2020
     */
    private Integer postid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.PostType
     *
     * @mbg.generated Wed Jun 10 22:24:16 CST 2020
     */
    private Integer posttype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.UserNo
     *
     * @mbg.generated Wed Jun 10 22:24:16 CST 2020
     */
    private String userno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.PostTitle
     *
     * @mbg.generated Wed Jun 10 22:24:16 CST 2020
     */
    private String posttitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.PostDetail
     *
     * @mbg.generated Wed Jun 10 22:24:16 CST 2020
     */
    private String postdetail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.ImgUrl
     *
     * @mbg.generated Wed Jun 10 22:24:16 CST 2020
     */
    private String imgurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.Goods
     *
     * @mbg.generated Wed Jun 10 22:24:16 CST 2020
     */
    private Integer goods;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.Bads
     *
     * @mbg.generated Wed Jun 10 22:24:16 CST 2020
     */
    private Integer bads;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.Time
     *
     * @mbg.generated Wed Jun 10 22:24:16 CST 2020
     */
    private Date time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.Status
     *
     * @mbg.generated Wed Jun 10 22:24:16 CST 2020
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.Comments
     *
     * @mbg.generated Wed Jun 10 22:24:16 CST 2020
     */
    private String comments;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.PostId
     *
     * @return the value of post.PostId
     *
     * @mbg.generated Wed Jun 10 22:24:16 CST 2020
     */
    public Integer getPostid() {
        return postid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.PostId
     *
     * @param postid the value for post.PostId
     *
     * @mbg.generated Wed Jun 10 22:24:16 CST 2020
     */
    public void setPostid(Integer postid) {
        this.postid = postid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.PostType
     *
     * @return the value of post.PostType
     *
     * @mbg.generated Wed Jun 10 22:24:16 CST 2020
     */
    public Integer getPosttype() {
        return posttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.PostType
     *
     * @param posttype the value for post.PostType
     *
     * @mbg.generated Wed Jun 10 22:24:16 CST 2020
     */
    public void setPosttype(Integer posttype) {
        this.posttype = posttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.UserNo
     *
     * @return the value of post.UserNo
     *
     * @mbg.generated Wed Jun 10 22:24:16 CST 2020
     */
    public String getUserno() {
        return userno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.UserNo
     *
     * @param userno the value for post.UserNo
     *
     * @mbg.generated Wed Jun 10 22:24:16 CST 2020
     */
    public void setUserno(String userno) {
        this.userno = userno == null ? null : userno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.PostTitle
     *
     * @return the value of post.PostTitle
     *
     * @mbg.generated Wed Jun 10 22:24:16 CST 2020
     */
    public String getPosttitle() {
        return posttitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.PostTitle
     *
     * @param posttitle the value for post.PostTitle
     *
     * @mbg.generated Wed Jun 10 22:24:16 CST 2020
     */
    public void setPosttitle(String posttitle) {
        this.posttitle = posttitle == null ? null : posttitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.PostDetail
     *
     * @return the value of post.PostDetail
     *
     * @mbg.generated Wed Jun 10 22:24:16 CST 2020
     */
    public String getPostdetail() {
        return postdetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.PostDetail
     *
     * @param postdetail the value for post.PostDetail
     *
     * @mbg.generated Wed Jun 10 22:24:16 CST 2020
     */
    public void setPostdetail(String postdetail) {
        this.postdetail = postdetail == null ? null : postdetail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.ImgUrl
     *
     * @return the value of post.ImgUrl
     *
     * @mbg.generated Wed Jun 10 22:24:16 CST 2020
     */
    public String getImgurl() {
        return imgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.ImgUrl
     *
     * @param imgurl the value for post.ImgUrl
     *
     * @mbg.generated Wed Jun 10 22:24:16 CST 2020
     */
    public void setImgurl(String imgurl) {
        this.imgurl = imgurl == null ? null : imgurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.Goods
     *
     * @return the value of post.Goods
     *
     * @mbg.generated Wed Jun 10 22:24:16 CST 2020
     */
    public Integer getGoods() {
        return goods;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.Goods
     *
     * @param goods the value for post.Goods
     *
     * @mbg.generated Wed Jun 10 22:24:16 CST 2020
     */
    public void setGoods(Integer goods) {
        this.goods = goods;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.Bads
     *
     * @return the value of post.Bads
     *
     * @mbg.generated Wed Jun 10 22:24:16 CST 2020
     */
    public Integer getBads() {
        return bads;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.Bads
     *
     * @param bads the value for post.Bads
     *
     * @mbg.generated Wed Jun 10 22:24:16 CST 2020
     */
    public void setBads(Integer bads) {
        this.bads = bads;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.Time
     *
     * @return the value of post.Time
     *
     * @mbg.generated Wed Jun 10 22:24:16 CST 2020
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.Time
     *
     * @param time the value for post.Time
     *
     * @mbg.generated Wed Jun 10 22:24:16 CST 2020
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.Status
     *
     * @return the value of post.Status
     *
     * @mbg.generated Wed Jun 10 22:24:16 CST 2020
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.Status
     *
     * @param status the value for post.Status
     *
     * @mbg.generated Wed Jun 10 22:24:16 CST 2020
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.Comments
     *
     * @return the value of post.Comments
     *
     * @mbg.generated Wed Jun 10 22:24:16 CST 2020
     */
    public String getComments() {
        return comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.Comments
     *
     * @param comments the value for post.Comments
     *
     * @mbg.generated Wed Jun 10 22:24:16 CST 2020
     */
    public void setComments(String comments) {
        this.comments = comments == null ? null : comments.trim();
    }
}