package com.example.campus.entity;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.NoArgsConstructor;

import java.util.Date;

@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Product {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.id
     *
     * @mbg.generated Sat Jun 06 21:31:09 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.title
     *
     * @mbg.generated Sat Jun 06 21:31:09 CST 2020
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.decription
     *
     * @mbg.generated Sat Jun 06 21:31:09 CST 2020
     */
    private String decription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.price
     *
     * @mbg.generated Sat Jun 06 21:31:09 CST 2020
     */
    private Double price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.type
     *
     * @mbg.generated Sat Jun 06 21:31:09 CST 2020
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.publish_time
     *
     * @mbg.generated Sat Jun 06 21:31:09 CST 2020
     */
    private Date publishTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.publish_userno
     *
     * @mbg.generated Sat Jun 06 21:31:09 CST 2020
     */
    private String publishUserno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.imgsrc
     *
     * @mbg.generated Sat Jun 06 21:31:09 CST 2020
     */
    private String imgsrc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.status
     *
     * @mbg.generated Sat Jun 06 21:31:09 CST 2020
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.flag
     *
     * @mbg.generated Sat Jun 06 21:31:09 CST 2020
     */
    private Integer flag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.id
     *
     * @return the value of product.id
     *
     * @mbg.generated Sat Jun 06 21:31:09 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.id
     *
     * @param id the value for product.id
     *
     * @mbg.generated Sat Jun 06 21:31:09 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.title
     *
     * @return the value of product.title
     *
     * @mbg.generated Sat Jun 06 21:31:09 CST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.title
     *
     * @param title the value for product.title
     *
     * @mbg.generated Sat Jun 06 21:31:09 CST 2020
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.decription
     *
     * @return the value of product.decription
     *
     * @mbg.generated Sat Jun 06 21:31:09 CST 2020
     */
    public String getDecription() {
        return decription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.decription
     *
     * @param decription the value for product.decription
     *
     * @mbg.generated Sat Jun 06 21:31:09 CST 2020
     */
    public void setDecription(String decription) {
        this.decription = decription == null ? null : decription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.price
     *
     * @return the value of product.price
     *
     * @mbg.generated Sat Jun 06 21:31:09 CST 2020
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.price
     *
     * @param price the value for product.price
     *
     * @mbg.generated Sat Jun 06 21:31:09 CST 2020
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.type
     *
     * @return the value of product.type
     *
     * @mbg.generated Sat Jun 06 21:31:09 CST 2020
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.type
     *
     * @param type the value for product.type
     *
     * @mbg.generated Sat Jun 06 21:31:09 CST 2020
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.publish_time
     *
     * @return the value of product.publish_time
     *
     * @mbg.generated Sat Jun 06 21:31:09 CST 2020
     */
    public Date getPublishTime() {
        return publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.publish_time
     *
     * @param publishTime the value for product.publish_time
     *
     * @mbg.generated Sat Jun 06 21:31:09 CST 2020
     */
    public void setPublishTime(Date publishTime) {
        this.publishTime = publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.publish_userno
     *
     * @return the value of product.publish_userno
     *
     * @mbg.generated Sat Jun 06 21:31:09 CST 2020
     */
    public String getPublishUserno() {
        return publishUserno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.publish_userno
     *
     * @param publishUserno the value for product.publish_userno
     *
     * @mbg.generated Sat Jun 06 21:31:09 CST 2020
     */
    public void setPublishUserno(String publishUserno) {
        this.publishUserno = publishUserno == null ? null : publishUserno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.imgsrc
     *
     * @return the value of product.imgsrc
     *
     * @mbg.generated Sat Jun 06 21:31:09 CST 2020
     */
    public String getImgsrc() {
        return imgsrc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.imgsrc
     *
     * @param imgsrc the value for product.imgsrc
     *
     * @mbg.generated Sat Jun 06 21:31:09 CST 2020
     */
    public void setImgsrc(String imgsrc) {
        this.imgsrc = imgsrc == null ? null : imgsrc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.status
     *
     * @return the value of product.status
     *
     * @mbg.generated Sat Jun 06 21:31:09 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.status
     *
     * @param status the value for product.status
     *
     * @mbg.generated Sat Jun 06 21:31:09 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.flag
     *
     * @return the value of product.flag
     *
     * @mbg.generated Sat Jun 06 21:31:09 CST 2020
     */
    public Integer getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.flag
     *
     * @param flag the value for product.flag
     *
     * @mbg.generated Sat Jun 06 21:31:09 CST 2020
     */
    public void setFlag(Integer flag) {
        this.flag = flag;
    }
}