package com.example.campus.entity;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
<<<<<<< HEAD
     * This field corresponds to the database column user.UserNo
     *
     * @mbg.generated Sat Jun 06 21:31:09 CST 2020
     */
    private String userno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.UserRealName
     *
     * @mbg.generated Sat Jun 06 21:31:09 CST 2020
=======
     * This field corresponds to the database column user.UserRealName
     *
     * @mbg.generated Tue Jun 02 17:06:36 CST 2020
>>>>>>> 45b1a026d333bb913c800a801d0cf78100269396
     */
    private String userrealname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.UserType
     *
<<<<<<< HEAD
     * @mbg.generated Sat Jun 06 21:31:09 CST 2020
=======
     * @mbg.generated Tue Jun 02 17:06:36 CST 2020
>>>>>>> 45b1a026d333bb913c800a801d0cf78100269396
     */
    private Integer usertype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Institute
     *
<<<<<<< HEAD
     * @mbg.generated Sat Jun 06 21:31:09 CST 2020
=======
     * @mbg.generated Tue Jun 02 17:06:36 CST 2020
>>>>>>> 45b1a026d333bb913c800a801d0cf78100269396
     */
    private String institute;

    /**
     *
     * This field was generated by MyBatis Generator.
<<<<<<< HEAD
     * This field corresponds to the database column user.IsResgister
     *
     * @mbg.generated Sat Jun 06 21:31:09 CST 2020
=======
     * This field corresponds to the database column user.UserNo
     *
     * @mbg.generated Tue Jun 02 17:06:36 CST 2020
     */
    private String userno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.IsResgister
     *
     * @mbg.generated Tue Jun 02 17:06:36 CST 2020
>>>>>>> 45b1a026d333bb913c800a801d0cf78100269396
     */
    private Integer isresgister;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Password
     *
<<<<<<< HEAD
     * @mbg.generated Sat Jun 06 21:31:09 CST 2020
=======
     * @mbg.generated Tue Jun 02 17:06:36 CST 2020
>>>>>>> 45b1a026d333bb913c800a801d0cf78100269396
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.UserName
     *
<<<<<<< HEAD
     * @mbg.generated Sat Jun 06 21:31:09 CST 2020
=======
     * @mbg.generated Tue Jun 02 17:06:36 CST 2020
>>>>>>> 45b1a026d333bb913c800a801d0cf78100269396
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Email
     *
<<<<<<< HEAD
     * @mbg.generated Sat Jun 06 21:31:09 CST 2020
=======
     * @mbg.generated Tue Jun 02 17:06:36 CST 2020
>>>>>>> 45b1a026d333bb913c800a801d0cf78100269396
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Address
     *
<<<<<<< HEAD
     * @mbg.generated Sat Jun 06 21:31:09 CST 2020
=======
     * @mbg.generated Tue Jun 02 17:06:36 CST 2020
>>>>>>> 45b1a026d333bb913c800a801d0cf78100269396
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Tel
     *
<<<<<<< HEAD
     * @mbg.generated Sat Jun 06 21:31:09 CST 2020
=======
     * @mbg.generated Tue Jun 02 17:06:36 CST 2020
>>>>>>> 45b1a026d333bb913c800a801d0cf78100269396
     */
    private String tel;

    /**
     * This method was generated by MyBatis Generator.
<<<<<<< HEAD
     * This method returns the value of the database column user.UserNo
     *
     * @return the value of user.UserNo
     *
     * @mbg.generated Sat Jun 06 21:31:09 CST 2020
     */
    public String getUserno() {
        return userno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.UserNo
     *
     * @param userno the value for user.UserNo
     *
     * @mbg.generated Sat Jun 06 21:31:09 CST 2020
     */
    public void setUserno(String userno) {
        this.userno = userno == null ? null : userno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
=======
>>>>>>> 45b1a026d333bb913c800a801d0cf78100269396
     * This method returns the value of the database column user.UserRealName
     *
     * @return the value of user.UserRealName
     *
<<<<<<< HEAD
     * @mbg.generated Sat Jun 06 21:31:09 CST 2020
=======
     * @mbg.generated Tue Jun 02 17:06:36 CST 2020
>>>>>>> 45b1a026d333bb913c800a801d0cf78100269396
     */
    public String getUserrealname() {
        return userrealname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.UserRealName
     *
     * @param userrealname the value for user.UserRealName
     *
<<<<<<< HEAD
     * @mbg.generated Sat Jun 06 21:31:09 CST 2020
=======
     * @mbg.generated Tue Jun 02 17:06:36 CST 2020
>>>>>>> 45b1a026d333bb913c800a801d0cf78100269396
     */
    public void setUserrealname(String userrealname) {
        this.userrealname = userrealname == null ? null : userrealname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.UserType
     *
     * @return the value of user.UserType
     *
<<<<<<< HEAD
     * @mbg.generated Sat Jun 06 21:31:09 CST 2020
=======
     * @mbg.generated Tue Jun 02 17:06:36 CST 2020
>>>>>>> 45b1a026d333bb913c800a801d0cf78100269396
     */
    public Integer getUsertype() {
        return usertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.UserType
     *
     * @param usertype the value for user.UserType
     *
<<<<<<< HEAD
     * @mbg.generated Sat Jun 06 21:31:09 CST 2020
=======
     * @mbg.generated Tue Jun 02 17:06:36 CST 2020
>>>>>>> 45b1a026d333bb913c800a801d0cf78100269396
     */
    public void setUsertype(Integer usertype) {
        this.usertype = usertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Institute
     *
     * @return the value of user.Institute
     *
<<<<<<< HEAD
     * @mbg.generated Sat Jun 06 21:31:09 CST 2020
=======
     * @mbg.generated Tue Jun 02 17:06:36 CST 2020
>>>>>>> 45b1a026d333bb913c800a801d0cf78100269396
     */
    public String getInstitute() {
        return institute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Institute
     *
     * @param institute the value for user.Institute
     *
<<<<<<< HEAD
     * @mbg.generated Sat Jun 06 21:31:09 CST 2020
=======
     * @mbg.generated Tue Jun 02 17:06:36 CST 2020
>>>>>>> 45b1a026d333bb913c800a801d0cf78100269396
     */
    public void setInstitute(String institute) {
        this.institute = institute == null ? null : institute.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
<<<<<<< HEAD
=======
     * This method returns the value of the database column user.UserNo
     *
     * @return the value of user.UserNo
     *
     * @mbg.generated Tue Jun 02 17:06:36 CST 2020
     */
    public String getUserno() {
        return userno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.UserNo
     *
     * @param userno the value for user.UserNo
     *
     * @mbg.generated Tue Jun 02 17:06:36 CST 2020
     */
    public void setUserno(String userno) {
        this.userno = userno == null ? null : userno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
>>>>>>> 45b1a026d333bb913c800a801d0cf78100269396
     * This method returns the value of the database column user.IsResgister
     *
     * @return the value of user.IsResgister
     *
<<<<<<< HEAD
     * @mbg.generated Sat Jun 06 21:31:09 CST 2020
=======
     * @mbg.generated Tue Jun 02 17:06:36 CST 2020
>>>>>>> 45b1a026d333bb913c800a801d0cf78100269396
     */
    public Integer getIsresgister() {
        return isresgister;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.IsResgister
     *
     * @param isresgister the value for user.IsResgister
     *
<<<<<<< HEAD
     * @mbg.generated Sat Jun 06 21:31:09 CST 2020
=======
     * @mbg.generated Tue Jun 02 17:06:36 CST 2020
>>>>>>> 45b1a026d333bb913c800a801d0cf78100269396
     */
    public void setIsresgister(Integer isresgister) {
        this.isresgister = isresgister;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Password
     *
     * @return the value of user.Password
     *
<<<<<<< HEAD
     * @mbg.generated Sat Jun 06 21:31:09 CST 2020
=======
     * @mbg.generated Tue Jun 02 17:06:36 CST 2020
>>>>>>> 45b1a026d333bb913c800a801d0cf78100269396
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Password
     *
     * @param password the value for user.Password
     *
<<<<<<< HEAD
     * @mbg.generated Sat Jun 06 21:31:09 CST 2020
=======
     * @mbg.generated Tue Jun 02 17:06:36 CST 2020
>>>>>>> 45b1a026d333bb913c800a801d0cf78100269396
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.UserName
     *
     * @return the value of user.UserName
     *
<<<<<<< HEAD
     * @mbg.generated Sat Jun 06 21:31:09 CST 2020
=======
     * @mbg.generated Tue Jun 02 17:06:36 CST 2020
>>>>>>> 45b1a026d333bb913c800a801d0cf78100269396
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.UserName
     *
     * @param username the value for user.UserName
     *
<<<<<<< HEAD
     * @mbg.generated Sat Jun 06 21:31:09 CST 2020
=======
     * @mbg.generated Tue Jun 02 17:06:36 CST 2020
>>>>>>> 45b1a026d333bb913c800a801d0cf78100269396
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Email
     *
     * @return the value of user.Email
     *
<<<<<<< HEAD
     * @mbg.generated Sat Jun 06 21:31:09 CST 2020
=======
     * @mbg.generated Tue Jun 02 17:06:36 CST 2020
>>>>>>> 45b1a026d333bb913c800a801d0cf78100269396
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Email
     *
     * @param email the value for user.Email
     *
<<<<<<< HEAD
     * @mbg.generated Sat Jun 06 21:31:09 CST 2020
=======
     * @mbg.generated Tue Jun 02 17:06:36 CST 2020
>>>>>>> 45b1a026d333bb913c800a801d0cf78100269396
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Address
     *
     * @return the value of user.Address
     *
<<<<<<< HEAD
     * @mbg.generated Sat Jun 06 21:31:09 CST 2020
=======
     * @mbg.generated Tue Jun 02 17:06:36 CST 2020
>>>>>>> 45b1a026d333bb913c800a801d0cf78100269396
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Address
     *
     * @param address the value for user.Address
     *
<<<<<<< HEAD
     * @mbg.generated Sat Jun 06 21:31:09 CST 2020
=======
     * @mbg.generated Tue Jun 02 17:06:36 CST 2020
>>>>>>> 45b1a026d333bb913c800a801d0cf78100269396
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Tel
     *
     * @return the value of user.Tel
     *
<<<<<<< HEAD
     * @mbg.generated Sat Jun 06 21:31:09 CST 2020
=======
     * @mbg.generated Tue Jun 02 17:06:36 CST 2020
>>>>>>> 45b1a026d333bb913c800a801d0cf78100269396
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Tel
     *
     * @param tel the value for user.Tel
     *
<<<<<<< HEAD
     * @mbg.generated Sat Jun 06 21:31:09 CST 2020
=======
     * @mbg.generated Tue Jun 02 17:06:36 CST 2020
>>>>>>> 45b1a026d333bb913c800a801d0cf78100269396
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }
}